src/Dockerfile.hpo
src/Dockerfile.search_space
src/build_hpo.sh
src/deploy_hpo.sh
src/hyperparameter_tuning/README.md
src/hyperparameter_tuning/bayes_optuna/README.md
src/hyperparameter_tuning/bayes_optuna/optuna_hpo.py
src/hyperparameter_tuning/json_validate.py
src/hyperparameter_tuning/logger.py
src/hyperparameter_tuning/service.py
src/hyperparameter_tuning/tunables.py
src/scripts/cluster-helpers.sh
src/scripts/search_space.py
src/scripts/search_space_service.py
src/tests/README.md
src/tests/resources/searchspace_jsons/searchspace.json
src/tests/scripts/functional_tests.sh
src/tests/scripts/hpo/constants/hpo_api_constants.sh
src/tests/scripts/hpo/hpo_api_tests.sh
src/tests/scripts/hpo/search_space.py
src/tests/scripts/hpo/start_hpo_servers.sh

Add basic files for hpo-aas

---

src/build_hpo.sh

Support building HPO container images with podman.
This change does not modify the current default behaviour

Automatically resolve available container runtime

---

src/bayes_optuna/optuna_hpo.py

Update sleep time to 1 sec in perform_experiment()

---

src/bayes_optuna/optuna_hpo.py
src/json_validate.py
src/service.py
src/tunables.py

Signed-off-by: kusumachalasani <kchalasa@redhat.com>

Use trials from searchspace

---

scripts/cluster-helpers.sh

Update script to terminate native app

---

Dockerfile.hpo
build_hpo.sh
deploy_hpo.sh
scripts/cluster-helpers.sh
src/bayes_optuna/optuna_hpo.py
src/hpo_service.py
src/json_validate.py
src/service.py
version.py

Add version file, update build parameters and other fixes

---

src/service.py

update hostname to 0.0.0.0

---

src/grpc_service.py

Return exception if incorrect Trial Number is passed into gRPC GetTrialConfig

---

src/README.md
src/bayes_optuna/optuna_hpo.py
src/gRPC/hpo_pb2.py
src/gRPC/hpo_pb2_grpc.py
src/gRPC/protos/hpo.proto
src/grpc_client.py
src/grpc_service.py
src/hpo_service.py

To return recommended configuration after an experiment has completed via gRPC service

Expose GetRecommendedConfig gRPC method 

---

.github/workflows/test_on_pr.yaml
tests/scripts/common/common_functions.sh
tests/scripts/hpo/hpo_api_tests.sh

Included grpc sanity tests in PR check for HPO

Included grpc sanity test in PR check for HPO

---

tests/README.md
tests/scripts/common/common_functions.sh
tests/scripts/hpo/hpo_api_tests.sh
tests/scripts/hpo/hpo_get_config_tests.sh
tests/scripts/hpo/hpo_multiple_exp_tests.sh
tests/scripts/hpo/hpo_post_exp_result_tests.sh
tests/scripts/hpo/hpo_post_experiment_tests.sh
tests/scripts/hpo/hpo_sanity_tests.sh
tests/test_hpo.sh

Enabled HPO tests to run on minikube cluster

Enabled HPO tests to run on minikube / openshift cluster

---

design/API.md
src/bayes_optuna/optuna_hpo.py
src/rest_service.py
src/utils.py

This PR aims to fix the issue #17 .
Updated the list having the supported types in the utils.py file

Fix Issue with prune trial result status 

---

tests/scripts/common/common_functions.sh
tests/scripts/functional_tests.sh
tests/scripts/hpo/hpo_multiple_exp_tests.sh
tests/scripts/hpo/hpo_sanity_tests.sh
tests/test_hpo.sh

Included namespace as a commandline option and removed unrequired code
Signed-off-by: Chandrakala Subramanyam <csubrama@redhat.com>

Included namespace as a commandline option and removed unrequired code

---

src/grpc_client.py
tests/scripts/hpo/hpo_sanity_tests.sh

This PR aims to resolve issue #71 
Updated the grpc_client to check for validation when the input JSON is passed.

Add JSON validation in gRPC code 

---

.github/workflows/test_on_pr.yaml
tests/scripts/common/common_functions.sh

Signed-off-by: Chandrakala Subramanyam <csubrama@redhat.com>

Included PR check for minikube

---

scripts/cluster-helpers.sh
scripts/openshift-helpers.sh

Expose Openshift service

---

version.py

Signed-off-by: Dinakar Guniguntala <dgunigun@redhat.com>

Update HPO version to 0.0.2

---

experiment.html
index.html
scripts/cluster-helpers.sh
src/bayes_optuna/optuna_hpo.py
src/rest_service.py

Description:
The following PR has commits related to:
1. View the experiment and plot details from the index page.
2. For tunable_importance, if there is runtime error generating the plot - the html shows the related error. For any other unavialable plots, updates as "Plot Unavailable! "

View experiment and plot details from index

---

tests/scripts/common/common_functions.sh
tests/scripts/hpo/constants/hpo_api_constants.sh
tests/scripts/hpo/hpo_api_tests.sh
tests/scripts/hpo/hpo_get_plot_tests.sh

Signed-off-by: Chandrakala Subramanyam <csubrama@redhat.com>

Included tests for plot API

---

.github/workflows/test_on_pr.yaml
Dockerfile.hpo
manifests/hpo-deployment.yaml_template
scripts/cluster-helpers.sh
scripts/openshift-helpers.sh

This PR aims to resolve issue #119 
- Modified the dockerFile to fix the permission issue which caused failure while deploying in openshift.
- Made the corresponding changes in the helper files to remove service account, rolebinding and others.

Modified dockerFile to fix openshift deployment issues

---

design/API.md

Adding missing quotes

---

README.md
manifests/kustomization.yaml

Updated readme to include operate first deployment

Updated README to include OperateFirst definition and added Kustomization.yaml for argoCD

---

index.html

update link to API docs
